language: php
php: 7
sudo: true

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - npm install
  - composer install --prefer-dist --no-dev

script: ./publish.sh

env:
  global:
    - ENCRYPTION_LABEL: 01701315b81b
    - COMMIT_AUTHOR_EMAIL: "oliver@oliverdavies.uk"
