language: php
php: 7
sudo: true

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - npm install
  - composer install --prefer-dist --no-dev

script:
  - ./publish.sh

env:
  global:
    secure: dDkWwZmpNILTnysDdKp6uhnQ+TtT/RbJyhMFc+YQKOvXH4hBoXFf+gGqzVPCGJDHiNhDR07w0oinYfeAw4Ap4MCGBT4X8LfNgvcakxdElZmsu/5ybebNKTkh12CR1jbRKwFyBhV5AWzDY0i0KSkjPZWMx7u4Nrhv53CGFCnIPns88vy8fb2OZvDF6EbUgLHAzE/9DscfDTIbuzrl0RA9UxFJa065d1HCZtGAieki19YrCFkG/ws7nYU4j6JxgywMwOQd8pZAjtEInOAFlks76zNPeqFrrebpet7Z+DE+oEDV5wg5zas2t9lS8ys5VElm8Lrgm0Flv1BfDz9yh67GqDULNGlEz0VSoGcMUV8E624U21EYtD3rxnnNASMedFqjAX4+vh/6/ZAe4X/lpjBZop/J5qPO5o84otj0Xvm71k4o1qCcyLTNWJTqU4WU1X/RH7wuHwTB5NjjN4PsHa9oYmDwPvciVBV6Br37W/S4OYdVAC0ueIEbLFY2Dcvvjpo2elAn95Wqqbb6pKbMowNnIOissFdQduL4DDiAm8qTm/REa3I4oTp91r5RVz6BY7YKLKgCWzTYWetsUXk7kUvO8KXj9Hq8I54YO2skO0+2ezyVAnguJ8ga++ss4f3wGrkdNvaTRNDR4bksPRQbMcamIOJ0m+k6eb2NuEf8w3SO1KU=
