language: php
php: 7

sudo: true

branches:
    only:
        - master

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - npm install
    - npm run prod
    - composer install --prefer-dist --no-dev

script:
    - ./publish.sh
