build:
  type: composer

redirects:
    "^/about": { to: "/" }
    "^/blog/10-useful-drupal-6-modules": { to: "/blog/2010/06/25/10-useful-drupal-6-modules" }
    "^/blog/2012/07/nomensa-accessible-media-player-drupal": { to: "/blog/install-nomensa-media-player-drupal/" }
    "^/blog/2017/05/05/fixing-drupal-simpletest-issues-inside-docker-containers": { to: "/blog/2017/05/05/fixing-drupal-simpletest-docker" }
    "^/blog/accessible-bristol-site-launched": { to: "/blog/2012/11/15/accessible-bristol-site-launched" }
    "^/blog/add-date-popup-calendar-custom-form": { to: "/blog/2012/05/23/add-date-popup-calendar-custom-form" }
    "^/blog/add-taxonomy-term-multiple-nodes-using-sql": { to: "/blog/2010/07/07/add-taxonomy-term-multiple-nodes-using-sql" }
    "^/blog/adding-custom-theme-templates-drupal-7": { to: "/blog/2012/04/19/adding-custom-theme-templates-drupal-7" }
    "^/blog/announcing-the-drupal-vm-config-generator": { to: "/blog/announcing-the-drupal-vm-generator" }
    "^/blog/announcing-the-drupal-vm-generator": { to: "/blog/2016/02/15/announcing-the-drupal-vm-generator" }
    "^/blog/automating-sculpin-jenkins": { to: "/blog/2015/07/21/automating-sculpin-jenkins" }
    "^/blog/building-gmail-filters-with-php": { to: "/blog/2016/07/15/building-gmail-filters-with-php" }
    "^/blog/change-content-type-multiple-nodes-using-sql": { to: "/blog/2010/07/01/change-content-type-multiple-nodes-using-sql" }
    "^/blog/checking-if-user-logged-drupal-right-way": { to: "/blog/2013/01/09/checking-if-user-logged-drupal-right-way" }
    "^/blog/checkout-specific-revision-svn-command-line": { to: "/blog/2012/05/23/checkout-specific-revision-svn-command-line" }
    "^/blog/conditional-email-addresses-webform": { to: "/blog/2010/05/06/conditional-email-addresses-webform" }
    "^/blog/create-a-zen-sub-theme-using-drush": { to: "/blog/2013/09/06/create-a-zen-sub-theme-using-drush" }
    "^/blog/create-and-apply-patches": { to: "/blog/2010/10/10/create-and-apply-patches" }
    "^/blog/create-better-photo-gallery-drupal-part-1": { to: "/blog/2010/08/11/create-better-photo-gallery-drupal-part-1" }
    "^/blog/create-better-photo-gallery-drupal-part-2": { to: "/blog/2010/08/17/create-better-photo-gallery-drupal-part-2" }
    "^/blog/create-better-photo-gallery-drupal-part-21": { to: "/blog/2010/10/22/create-better-photo-gallery-drupal-part-21" }
    "^/blog/create-better-photo-gallery-drupal-part-3": { to: "/blog/2010/10/13/create-better-photo-gallery-drupal-part-3" }
    "^/blog/create-block-social-media-icons-using-cck-views-and-nodequeue": { to: "/blog/2010/06/23/create-block-social-media-icons-using-cck-views-and-nodequeue" }
    "^/blog/create-flickr-photo-gallery-using-feeds-cck-and-views": { to: "/blog/2010/06/28/create-flickr-photo-gallery-using-feeds-cck-and-views" }
    "^/blog/create-multigroups-drupal-7-using-field-collections": { to: "/blog/2011/08/28/create-multigroups-drupal-7-using-field-collections" }
    "^/blog/create-omega-subtheme-less-css-preprocessor-using-omega-tools-and-drush": { to: "/blog/2012/04/16/create-omega-subtheme-less-css-preprocessor-using-omega-tools-and-drush" }
    "^/blog/create-slideshow-multiple-images-using-fancy-slide": { to: "/blog/2010/05/25/create-slideshow-multiple-images-using-fancy-slide" }
    "^/blog/create-virtual-hosts-mac-os-x-using-virtualhostx": { to: "/blog/2010/07/02/create-virtual-hosts-mac-os-x-using-virtualhostx" }
    "^/blog/creating-and-using-custom-tokens-drupal-7": { to: "/blog/2013/02/16/creating-and-using-custom-tokens-drupal-7" }
    "^/blog/creating-local-and-staging-sites-drupals-domain-module-enabled": { to: "/blog/2013/07/17/creating-local-and-staging-sites-drupals-domain-module-enabled" }
    "^/blog/display-custom-menu-drupal-7-theme-template-file": { to: "/blog/2012/08/18/display-custom-menu-drupal-7-theme-template-file" }
    "^/blog/display-git-branch-or-tag-names-your-bash-prompt": { to: "/blog/2013/04/27/display-git-branch-or-tag-names-your-bash-prompt" }
    "^/blog/display-number-facebook-fans-php": { to: "/blog/2011/03/15/display-number-facebook-fans-php" }
    "^/blog/dividing-drupals-process-and-preprocess-functions-separate-files": { to: "/blog/2012/05/24/dividing-drupals-process-and-preprocess-functions-separate-files" }
    "^/blog/dont-bootstrap-drupal-use-drush": { to: "/blog/2013/11/19/dont-bootstrap-drupal-use-drush" }
    "^/blog/download-different-versions-drupal-drush": { to: "/blog/2013/12/31/download-different-versions-drupal-drush" }
    "^/blog/drupal-association": { to: "/blog/2014/05/03/drupal-association" }
    "^/blog/drupal-vm-generator-291-released": { to: "/blog/2016/12/30/drupal-vm-generator-291-released" }
    "^/blog/drupalcamp-london-2014": { to: "/blog/2014/02/09/drupalcamp-london-2014" }
    "^/blog/drush-make-drupalbristol": { to: "/blog/2014/07/02/drush-make-drupalbristol" }
    "^/blog/easier-sculpin-commands-with-composer-and-npm-scripts": { to: "/blog/2017/01/07/easier-sculpin-commands-with-composer-and-npm-scripts" }
    "^/blog/easily-embed-typekit-fonts-your-drupal-website": { to: "/blog/2011/02/14/easily-embed-typekit-fonts-your-drupal-website" }
    "^/blog/fix-vagrant-loading-wrong-virtual-machine": { to: "/blog/2014/10/06/fix-vagrant-loading-wrong-virtual-machine" }
    "^/blog/forward-one-domain-another-using-modrewrite-and-htaccess": { to: "/blog/2012/05/23/forward-one-domain-another-using-modrewrite-and-htaccess" }
    "^/blog/git-format-patch": { to: "/blog/2014/05/21/git-format-patch" }
    "^/blog/going-drupalcon": { to: "/blog/2013/07/26/going-drupalcon" }
    "^/blog/how-to-define-a-minimum-drupal-core-version": { to: "/blog/2015/04/03/how-to-define-a-minimum-drupal-core-version" }
    "^/blog/imagefield-import-archive": { to: "/blog/2011/05/23/imagefield-import-archive" }
    "^/blog/improve-jpg-quality-imagecache-and-imageapi": { to: "/blog/2010/06/02/improve-jpg-quality-imagecache-and-imageapi" }
    "^/blog/include-css-fonts-using-sass-each-loop": { to: "/blog/2014/11/18/include-css-fonts-using-sass-each-loop" }
    "^/blog/include-local-drupal-settings-file-environment-configuration-and-overrides": { to: "/blog/2014/12/20/include-local-drupal-settings-file-environment-configuration-and-overrides" }
    "^/blog/install-and-configure-subversion-svn-server-ubuntu": { to: "/blog/2011/10/19/install-and-configure-subversion-svn-server-ubuntu" }
    "^/blog/install-nomensa-media-player-drupal": { to: "/blog/2012/07/14/install-nomensa-media-player-drupal" }
    "^/blog/installing-nagios-centos": { to: "/blog/2012/04/17/installing-nagios-centos" }
    "^/blog/leaving-nomensa-joining-precedent": { to: "/blog/2013/04/20/leaving-nomensa-joining-precedent" }
    "^/blog/my-new-drupal-modules": { to: "/blog/2012/07/12/my-new-drupal-modules" }
    "^/blog/my-sublime-text-2-settings": { to: "/blog/2012/10/25/my-sublime-text-2-settings" }
    "^/blog/nginx-redirects-with-query-string-arguments": { to: "/blog/2017/01/31/nginx-redirects-with-query-string-arguments" }
    "^/blog/open-sublime-text-2-mac-os-x-command-line": { to: "/blog/2012/11/17/open-sublime-text-2-mac-os-x-command-line" }
    "^/blog/pantheon-settings-files": { to: "/blog/2014/11/27/pantheon-settings-files" }
    "^/blog/prevent-apache-displaying-text-files-within-web-browser": { to: "/blog/2012/05/23/prevent-apache-displaying-text-files-within-web-browser" }
    "^/blog/proctor-stevenson": { to: "/blog/2011/03/31/proctor-stevenson" }
    "^/blog/proctors-hosting-next-drupal-meetup": { to: "/blog/2011/05/20/proctors-hosting-next-drupal-meetup" }
    "^/blog/programmatically-load-an-entityform-in-drupal-7": { to: "/blog/2015/12/22/programmatically-load-an-entityform-in-drupal-7" }
    "^/blog/quickest-way-install-sublime-text-2-ubuntu": { to: "/blog/2013/03/02/quickest-way-install-sublime-text-2-ubuntu" }
    "^/blog/quickly-apply-patches-using-git-and-curl-or-wget": { to: "/blog/2013/12/24/quickly-apply-patches-using-git-and-curl-or-wget" }
    "^/blog/quickly-create-zen-subthemes-using-zenophile": { to: "/blog/2010/05/10/quickly-create-zen-subthemes-using-zenophile" }
    "^/blog/quickly-import-multiples-images-using-imagefieldimport-module": { to: "/blog/2010/05/29/quickly-import-multiples-images-using-imagefieldimport-module" }
    "^/blog/reflections-speaking-unifieddiff": { to: "/blog/2012/09/06/reflections-speaking-unifieddiff" }
    "^/blog/review-adminhover-module": { to: "/blog/2010/08/10/review-adminhover-module" }
    "^/blog/review-image-caption-module": { to: "/blog/2010/08/20/review-image-caption-module" }
    "^/blog/review-teleport-module": { to: "/blog/2010/07/12/review-teleport-module" }
    "^/blog/sculpin-twig-resources": { to: "/blog/2015/07/19/sculpin-twig-resources" }
    "^/blog/simplifying-drupal-migrations-with-xautoload": { to: "/blog/2016/05/03/simplifying-drupal-migrations-with-xautoload" }
    "^/blog/site-upgraded-drupal-7": { to: "/blog/2012/01/04/site-upgraded-drupal-7" }
    "^/blog/some-useful-git-aliases": { to: "/blog/2014/01/15/some-useful-git-aliases" }
    "^/blog/some-useful-links-using-simpletest-drupal": { to: "/blog/2013/06/13/some-useful-links-using-simpletest-drupal" }
    "^/blog/south-wales-drupal-user-group": { to: "/blog/2010/09/26/south-wales-drupal-user-group" }
    "^/blog/style-drupal-6s-taxonomy-lists-php-css-and-jquery": { to: "/blog/2010/04/05/style-drupal-6s-taxonomy-lists-php-css-and-jquery" }
    "^/blog/thanks": { to: "/blog/2014/05/06/thanks" }
    "^/blog/updating-features-and-adding-components-using-drush": { to: "/blog/2014/10/21/updating-features-and-adding-components-using-drush" }
    "^/blog/updating-forked-repositories-on-github": { to: "/blog/2015/06/18/updating-forked-repositories-on-github" }
    "^/blog/use-authorized-keys-create-passwordless-ssh-connection": { to: "/blog/2012/02/01/use-authorized-keys-create-passwordless-ssh-connection" }
    "^/blog/use-regular-expressions-search-and-replace-coda-or-textmate": { to: "/blog/2010/11/04/use-regular-expressions-search-and-replace-coda-or-textmate" }
    "^/blog/use-sass-and-compass-drupal-7-using-sassy": { to: "/blog/2012/12/06/use-sass-and-compass-drupal-7-using-sassy" }
    "^/blog/useful-vagrant-commands": { to: "/blog/2013/11/27/useful-vagrant-commands" }
    "^/blog/using-imagecache-and-imagecrop-my-portfolio": { to: "/blog/2010/04/28/using-imagecache-and-imagecrop-my-portfolio" }
    "^/blog/using-remote-files-when-developing-locally-with-stage-file-proxy-module": { to: "/blog/2014/11/20/using-remote-files-when-developing-locally-with-stage-file-proxy-module" }
    "^/blog/what-git-flow": { to: "/blog/2014/03/03/what-git-flow" }
    "^/blog/writing-article-linux-journal": { to: "/blog/2012/07/27/writing-article-linux-journal" }
    "^/blog/writing-info-file-drupal-7-theme": { to: "/blog/2012/05/23/writing-info-file-drupal-7-theme" }
    "^/consulting": { to: "/" }
    "^/cv": { to: "https://gitprint.com/opdavies/cv/blob/master/README.md" }
    "^/drupalgive": { to: "https://www.drupal.org/u/opdavies" }
    "^/git-flow": { to: "/talks/git-flow" }
    "^/portfolio": { to: "/projects" }
    "^/services": { to: "/experience" }
    "^/slides/bristol-dug/drupal-vm-generator": { to: "http://opdavies.github.io/slides-drupal-vm-generator" }
    "^/slides/phpsw/building-static-websites-with-sculpin": { to: "https://opdavies.github.io/slides-phpsw-sculpin" }
    "^/speaking": { to: "/talks" }
    "^/talks/2012/09/05/what-is-this-drupal-thing-unified-diff": { to: "/talks/what-is-this-drupal-thing" }
    "^/talks/2013/07/10/drupal-ldap-swdug": { to: "/talks/drupal-ldap" }
    "^/talks/2014/03/01/git-flow-drupalcamp-london-2014": { to: "/talks/git-flow" }
    "^/talks/2014/07/02/drush-make-drupalbristol-drupal-bristol": { to: "/talks/drush-make-drupalbristol" }
    "^/talks/2014/08/19/drupal-association-swdug": { to: "/talks/drupal-association" }
    "^/talks/2015/01/18/drupalorg-2015-drupalcamp-brighton-2015": { to: "/talks/drupalorg-in-2015-whats-coming-next" }
    "^/talks/2015/02/28/drupalorg-2015-drupalcamp-london-2015": { to: "/talks/drupalorg-in-2015-whats-coming-next" }
    "^/talks/2015/04/08/drupal-8-phpsw": { to: "/talks/drupal-8" }
    "^/talks/2015/07/25/test-drive-twig-with-sculpin-drupalcamp-north-2015": { to: "/talks/test-drive-twig-with-sculpin" }
    "^/talks/2015/08/25/dancing-for-drupal-umbristol": { to: "/talks/dancing-for-drupal" }
    "^/talks/2015/10/14/sculpin-phpsw": { to: "/talks/sculpin" }
    "^/talks/2016/03/05/drupal-8-module-development-drupalcamp-london-2016": { to: "/talks/getting-started-with-drupal-8-module-development" }
    "^/talks/2016/03/09/drupal-vm-generator-nwdug": { to: "/talks/drupal-vm-generator" }
    "^/talks/2016/04/02/drupal-vm-generator-drupal-bristol": { to: "/talks/drupal-vm-generator" }
    "^/talks/2016/06/11/drupal-8-rejoining-the-herd-php-south-coast-2016": { to: "/talks/drupal-8-rejoining-the-herd" }
    "^/talks/2016/07/23/drupal-vm-meet-symfony-console-drupalcamp-bristol-2016": { to: "/talks/drupal-vm-meet-symfony-console" }
    "^/talks/2016/11/09/drupal-development-with-composer-phpsw": { to: "/talks/drupal-development-with-composer" }
    "^/talks/2016/11/17/goodbye-drush-make-hello-composer-drupal-bristol": { to: "/talks/goodbye-drush-make-hello-composer" }
    "^/talks/2017/01/18/getting-your-data-into-drupal-8-drupal-bristol": { to: "/talks/getting-your-data-into-drupal-8" }
    "^/talks/2017/03/04/getting-your-data-into-drupal-8-drupalcamp-london-2017": { to: "/talks/getting-your-data-into-drupal-8" }
    "^/talks/drupal-vm-generator-2": { to: "/talks/drupal-vm-generator" }
    "^/talks/drupalorg-2015": { to: "/talks/drupalorg-in-2015-whats-coming-next" }
    "^/talks/drupalorg-2015-2": { to: "/talks/drupalorg-in-2015-whats-coming-next" }
    "^/terms-and-conditions": { to: "/terms" }
    "^/work": { to: "/experience" }

hooks:
    build: |
        vendor/bin/sculpin generate --env=prod
        yarn --pure-lockfile
        node_modules/.bin/bower install
        node_modules/.bin/gulp --production

deploy:
    type: rsync
