api: '1'

sculpin:
  theme:
    build:
      bower: no
      npm: no
      type: gulp
      yarn: yes
    path: ~

composer:
  install: yes

# redirects:
#     "^/cv": { to: "https://gitprint.com/opdavies/cv/blob/master/README.md" }
#     "^/drupalgive": { to: "https://www.drupal.org/u/opdavies" }

deploy:
  restart_php: false
  restart_webserver: true
  rsync:
    options: '-vzcrSLh'
    delete: true
  type: rsync
