api: '1'

sculpin:
  theme:
    build:
      bower: yes
      npm: no
      type: gulp
      yarn: yes
    path: ~

composer:
  install: yes

deploy:
  restart_php: false
  restart_webserver: true
  rsync:
    # local_dir:
    # remote_dir: 
    options: '-vzcrSLh'
    delete: true
  type: rsync
