[build]
command = """
composer test && \
  npm run lint --fix-dry-run && \
  npm run build && \
  composer build
"""
publish = "output_prod"
environment = { PHP_VERSION = "7.2", YARN_VERSION = "1.13.0" }
