[build]
command = """
composer test \
  && composer prod \
  && npm run lint --fix-dry-run \
  && npm run prod \
  && cp -R source/dist output_prod
"""
publish = "output_prod"
environment = { PHP_VERSION = "7.2", YARN_VERSION = "1.13.0" }
