sculpin_content_types:
    posts:
        permalink: blog/:slug_title/
        taxonomies:
            - tags
    talks:
        permalink: talks/:year/:month/:day/:slug_title/
        taxonomies:
            - tags
