title: 'Oliver Davies'
subtitle: 'Web Developer, System Administrator - PHP, Drupal, Symfony, Linux'
description: 'Oliver Davies, Drupal Developer'
default_date_format: 'jS F, Y'
fuzzy_date_format: F Y
apple_touch_icon_sizes: [ 57, 114, 72, 144, 60, 120, 76, 152 ]
favicon_sizes: [ 160, 96, 32, 16 ]

ansible_galaxy:
    url: https://galaxy.ansible.com/opdavies

availability:
    part: limited
    full: no

avatar:
    url: /assets/images/me-precedent.jpg

companies:
    appnovation:
        name: Appnovation
        logo: appnovation.png
        url: 'https://www.appnovation.com'
    cti:
        name: CTI Digital
        logo: cti-digital.png
        url: 'https://www.ctidigital.com'
    drupal_association: 
        name: Drupal Association
        logo: drupal-association.png
        url: 'https://assoc.drupal.org'
    freelance:
        name: Freelance
        logo: ~
        url: ~
    horse_country:
        name: 'Horse & Country TV'
        logo: horse-and-country.jpg
        url: 'http://www.horseandcountry.tv'
    lab_class:
        name: Lab Class
        logo: lab-class.png
        url: 'http://labclass.co.uk'
    microserve:
        name: Microserve
        logo: microserve.png
        url: 'https://microserve.io'
    nomensa:
        name: Nomensa
        logo: nomensa.png
        url: 'http://www.nomensa.com'
    precedent:
        name: Precedent
        logo: precedent.jpg
        url: 'http://precedent.com'
    proctors: 
        name: 'Proctor & Stevenson'
        logo: proctors.jpg
        url: 'http://www.proctors.co.uk'
    trent:
        name: Trent Design
        logo: ~
        url: 'http://www.trentdesign.net'
    zooba:
        name: Zooba Ltd
        logo: ~
        url: ~

drupalorg:
    name: opdavies
    uid: 381388
    url: https://www.drupal.org/user/381388
    url_new: https://www.drupal.org/u/opdavies

email: oliver+website@oliverdavies.uk

events:
    drupal-bristol:
        title: Drupal Bristol
        location: 'Bristol, UK'
        url: 'https://www.drupalbristol.org.uk'
    drupalcamp-brighton-15:
        title: DrupalCamp Brighton 2015
        location: 'Brighton, UK'
        url: ~
    drupalcamp-bristol-16:
        title: DrupalCamp Bristol 2016
        location: 'Bristol, UK'
        url: 'https://www.drupalcampbristol.org.uk'
    drupalcamp-london-14:
        title: DrupalCamp London 2014
        location: 'London, UK'
        url: ~
    drupalcamp-london-15:
        title: DrupalCamp London 2015
        location: 'London, UK'
        url: ~
    drupalcamp-london-16:
        title: DrupalCamp London 2016
        location: 'London, UK'
        url: ~
    drupalcamp-london-17:
        title: DrupalCamp London 2017
        location: 'London, UK'
        url: 'https://drupalcamp.london'
    drupalcamp-north-15:
        title: DrupalCamp North 2015
        location: 'Sunderland, UK'
        url: 'http://drupalcampnorth.org'
    nomad_php:
        title: Nomad PHP
        location: Online
        url: 'https://nomadphp.com'
    nwdug:
        title: NWDUG
        location: 'Manchester, UK'
        url: 'http://nwdrupal.org.uk'
    phpsc-16:
        title: PHP South Coast 2016
        location: 'Portsmouth, UK'
        url: 'http://2016.phpsouthcoast.co.uk'
    phpsw:
        title: PHPSW
        location: 'Bristol, UK'
        url: 'https://phpsw.uk'
    swdug:
        title: SWDUG
        location: 'Cardiff, UK'
        url: ~
    udiff:
        title: Unified Diff
        location: 'Cardiff, UK'
        url: 'http://unifieddiff.co.uk'
    umbristol:
        title: umBristol
        location: 'Bristol, UK'
        url: 'http://umbristol.co.uk'

github:
    name: opdavies
    url: http://github.com/opdavies

gravatar:
    url: //www.gravatar.com/avatar/e0f6adcd63d8393e689b327e978d0887.png

irc:
    name: opdavies

joindin:
    url: https://joind.in/user/opdavies

lanyrd:
    url: http://lanyrd.com/profile/opdavies

latest_posts: 3

linkedin:
    url: http://uk.linkedin.com/in/opdavies

meetups:
    - name: Drupal Bristol
      logo: drupal-bristol.jpeg
      url: 'http://www.drupalbristol.org.uk'
    - name: DrupalCamp Bristol
      logo: drupalcamp-bristol.png
      url: 'http://www.drupalcampbristol.co.uk'
    - name: PHPSW
      logo: phpsw.jpeg
      url: 'http://phpsw.uk'

packagist:
    name: opdavies
    url: https://packagist.org/users/opdavies

skills:
    0:
        - { name: Drupal, image: drupal.png }
        - { name: Drupal Commerce, image: drupal-commerce.png }
        - { name: PHP, image: php.png }
        - { name: Composer, image: composer.png }
        - { name: Symfony, image: symfony.png }
        - { name: Silex, image: silex.png }
        - { name: Sculpin, image: sculpin.png }
        - { name: Twig, image: twig.png }
        - { name: PHPUnit, image: phpunit.png }
        - { name: SimpleTest, image: simpletest.png }
        - { name: Behat, image: behat.png }
        - { name: Gulp, image: gulp.png }
        - { name: Bower, image: bower.png }
        - { name: NPM, image: npm.png }
        - { name: Sass, image: sass.png }
        - { name: jQuery, image: jquery.gif }
        - { name: Git, image: git.png }
        - { name: Linux, image: linux.png }
        - { name: Debian, image: debian.png }
        - { name: Ubuntu, image: ubuntu.png }
        - { name: CentOS, image: centos.png }
        - { name: Vagrant, image: vagrant.png }
        - { name: Docker, image: docker.png }
        - { name: Nginx, image: nginx.png }
        - { name: MySQL, image: mysql.png }
        - { name: MariaDB, image: mariadb.png }
        - { name: Ansible, image: ansible.png }
        - { name: Fabric, image: fabric.png }
        - { name: Jenkins, image: jenkins.png }
        - { name: Acquia, image: acquia.png }
        - { name: Pantheon, image: pantheon.png }
        - { name: 'Platform.sh', image: platform.png }
        - { name: Amazon AWS, image: amazon.png }
        - { name: Linode, image: linode.png }
    1:
        - { name: Ubercart, image: ubercart.png }
        - { name: WordPress, image: wordpress.png }
        - { name: Jekyll, image: jekyll.png }
        - { name: Subversion, image: svn.jpg }
        - { name: Grunt, image: grunt.png }
        - { name: Less, image: less.png }
        - { name: Compass, image: compass.png }
        - { name: Puppet, image: puppet.png }
        - { name: Apache, image: apache.png }
        - { name: Apache Solr, image: solr.png }
    2:
        - { name: Laravel, image: laravel.png }
        - { name: Lumen, image: lumen.png }

speakerdeck:
    url: https://speakerdeck.com/opdavies

twitter:
    name: opdavies
    url: https://twitter.com/opdavies

wordpress:
    name: opdavies
    url: https://profiles.wordpress.org/opdavies

youtube:
    channel_url: https://www.youtube.com/channel/UCkeK0qF9HHUPQH_fvn4ghqQ

work:
    role: Senior Developer
    company: microserve
