title: Oliver Davies
subtitle: Full Stack Web Developer (Drupal, Symfony, Laravel, Linux)
description: 'Oliver Davies, Drupal Developer'
default_date_format: 'jS F, Y'
fuzzy_date_format: F Y
apple_touch_icon_sizes: [ 57, 114, 72, 144, 60, 120, 76, 152 ]
favicon_sizes: [ 160, 96, 32, 16 ]

author: Oliver Davies

availability:
    part: no
    full: no

avatar:
    url: /images/me-precedent.jpg

email: oliver+url@oliverdavies.uk

favicon:
    url: /images/me-phpnw.png

irc:
    name: opdavies

latest_posts: 5

work:
    role: Senior Developer
    company: microserve

imports:
    - '../../data/companies.yml'
    - '../../data/events.yml'
    - '../../data/links.yml'
