sculpin:
    ignore: ['**/.DS*', '**/*.swp']

sculpin_content_types:
    posts:
        permalink: blog/:basename/
        taxonomies: [tags]
    talks:
        permalink: talks/:basename/
        taxonomies: [tags]
