sculpin_content_types:
    posts:
        permalink: blog/:slug_title/
        taxonomies:
            - tags
    projects:
        permalink: projects/:slug_title/
        taxonomies:
            - tags
    talks:
        permalink: talks/:filename/
        taxonomies:
            - tags
