title: Oliver Davies
subtitle: Full Stack Web Developer (Drupal, Symfony, Laravel, Linux)
description: 'Oliver Davies, Drupal Developer'
default_date_format: 'jS F, Y'
fuzzy_date_format: F Y
apple_touch_icon_sizes: [ 57, 114, 72, 144, 60, 120, 76, 152 ]
favicon_sizes: [ 160, 96, 32, 16 ]

ansible_galaxy:
    url: https://galaxy.ansible.com/opdavies

author: Oliver Davies

availability:
    part: no
    full: no

avatar:
    url: /build/static/images/me-precedent.jpg

drupalorg:
    name: opdavies
    uid: 381388
    url: https://www.drupal.org/user/381388
    url_new: https://www.drupal.org/u/opdavies

email: oliver+website@oliverdavies.uk

favicon:
    url: /build/static/images/me-phpnw.png

github:
    name: opdavies
    url: http://github.com/opdavies

gravatar:
    url: //www.gravatar.com/avatar/e0f6adcd63d8393e689b327e978d0887.png

irc:
    name: opdavies

joindin:
    url: https://joind.in/user/opdavies

lanyrd:
    url: http://lanyrd.com/profile/opdavies

latest_posts: 5

linkedin:
    url: http://uk.linkedin.com/in/opdavies

packagist:
    name: opdavies
    url: https://packagist.org/users/opdavies

speakerdeck:
    url: https://speakerdeck.com/opdavies

twitter:
    name: opdavies
    url: https://twitter.com/opdavies

wordpress:
    name: opdavies
    url: https://profiles.wordpress.org/opdavies

youtube:
    channel_url: https://www.youtube.com/channel/UC5QoKapQ4bXOVMvN_ng_TYw

work:
    role: Senior Developer
    company: microserve

imports:
    - '../../data/companies.yml'
    - '../../data/events.yml'
    - '../../data/meetups.yml'
    - '../../data/navigation.yml'
