title: Oliver Davies
subtitle: Full Stack Web Developer (Drupal, Symfony, Laravel, Linux)
description: 'Oliver Davies, Drupal Developer'
email: oliver+website@oliverdavies.uk
apple_touch_icon_sizes: [ 57, 114, 72, 144, 60, 120, 76, 152 ]
favicon_sizes: [ 160, 96, 32, 16 ]

author: Oliver Davies

avatar:
    url: /images/me-precedent.jpg

favicon:
    url: /images/me-phpnw.png

imports:
    - data/availability.yml
    - data/companies.yml
    - data/events.yml
    - data/links.yml
    - data/menus.yml
    - data/work.yml

messages:
    - enabled: true
      start: 2020-02-01
      end: 2020-03-16
      text: |
          Oliver is giving a workshop, 'Automated Testing and Test Driven Development with Drupal 8' next month at [DrupalCamp London](https://drupalcamp.london). Find out more!
      paths:
          - /^\/(articles|talks)\/.+$/

    - enabled: false
      start: 2020-03-01
      end: 2020-03-16
      text: |
          Oliver is giving a workshop, 'Automated Testing and Test Driven Development with Drupal 8' this month at [DrupalCamp London](https://drupalcamp.london). Find out more!
      paths:
          - /^\/(articles|talks)\/.+$/
