title: 'Oliver Davies'
subtitle: 'Web Developer, System Administrator - PHP, Drupal, Symfony, Linux'
description: 'Oliver Davies, Drupal Developer'
default_date_format: 'jS F, Y'
fuzzy_date_format: F Y
apple_touch_icon_sizes: [ 57, 114, 72, 144, 60, 120, 76, 152 ]
favicon_sizes: [ 160, 96, 32, 16 ]

ansible_galaxy:
    url: https://galaxy.ansible.com/opdavies

author:
    name: Oliver Davies
    bio: 'Oliver Davies is a Drupal Developer and System Administrator based in the UK. He is a Senior Developer at <a href="https://www.appnovation.com">Appnovation Technologies</a> and also provides freelance consultancy services for Drupal websites, PHP applications and Linux servers.'
    company:
        logo: appnovation.png
        name: Appnovation Technologies
        name_short: Appnovation
        role: Senior Drupal Developer
        website: https://www.appnovation.com

availability: |
    <p><i class="fa fa-thumbs-o-down text-danger"></i> Not available for day contract work</p>
    <p><i class="fa fa-thumbs-o-up text-warning"></i> Limited availability for weekend/evening freelance work</p>

companies:
    appnovation:
        title: Appnovation Technologies
        website: https://www.appnovation.com
        logo: appnovation.png
    cti:
        title: CTI Digital
        website: https://www.ctidigital.com
        logo: cti-digital.png
    drupal_association:
        title: Drupal Association
        website: https://assoc.drupal.org
        logo: drupal-association.png
    freelance:
        title: Freelance
    horse_country:
        title: 'Horse & Country TV'
        logo: horse-and-country.jpg
        website: http://www.horseandcountry.tv
    lab_class:
        title: Lab Class
        website: http://labclass.co.uk
        logo: lab-class.png
    microserve:
        title: Microserve
        website: https://microserve.io
        logo: microserve.png
    nomensa:
        title: Nomensa
        website: http://www.nomensa.com
        logo: nomensa.png
    precedent:
        title: Precedent
        website: http://precedent.com
        logo: precedent.jpg
    proctors:
        title: 'Proctor & Stevenson'
        website: http://www.proctors.co.uk
        logo: proctors.jpg
    trent:
        title: Trent Design
        website: http://www.trentdesign.net
    zooba:
        title: Zooba Ltd

drupalorg:
    name: opdavies
    uid: 381388
    url: https://www.drupal.org/user/381388
    url_nice: https://www.drupal.org/u/opdavies

email: oliver+website@oliverdavies.uk

github:
    name: opdavies
    url: http://github.com/opdavies

gravatar:
    url: //www.gravatar.com/avatar/e0f6adcd63d8393e689b327e978d0887.png

irc:
    name: opdavies

joindin:
    url: https://joind.in/user/opdavies

lanyrd:
    url: http://lanyrd.com/profile/opdavies

linkedin:
    url: http://uk.linkedin.com/in/opdavies

main_menu:
    about: { href: /, title: About }
    talks: { href: /talks/, title: Talks }
    experience: { href: /experience/, title: Experience }
    blog: { href: /blog/, title: Blog }

meetups:
    drupalbristol:
        name: Drupal Bristol
        logo: drupal-bristol.jpeg
        website: http://www.drupalbristol.org.uk
    drupalcampbristol:
        name: DrupalCamp Bristol
        website: http://www.drupalcampbristol.co.uk
        logo: drupalcamp-bristol.png
    swdug:
        name: SWDUG
        logo: swdug.png
        website: http://swdug.org.uk
    phpsw:
        name: PHPSW
        logo: phpsw.jpeg
        website: http://phpsw.uk

packagist:
    name: opdavies
    url: https://packagist.org/users/opdavies

skills:
    compass: { title: Compass, image: compass.png }
    drupal: { title: Drupal, image: drupal.png }
    drupal-commerce: { title: Drupal Commerce, image: drupal-commerce.png }
    git: { title: Git, image: git.png }
    jenkins: { title: Jenkins, image: jenkins.png }
    less: { title: Less, image: less.png }
    php: { title: PHP, image: php.png }
    sass: { title: Sass, image: sass.png }
    svn: { title: Subversion, image: svn.jpg }

speakerdeck:
    url: https://speakerdeck.com/opdavies

twitter:
    name: opdavies
    url: https://twitter.com/opdavies

youtube:
    channel_url: https://www.youtube.com/channel/UCkeK0qF9HHUPQH_fvn4ghqQ
