sculpin:
    ignore: ['**/.DS*', '**/*.swp']
sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:slug_title/
        taxonomies: [tags]
    talks:
        permalink: talks/:basename/
        taxonomies: [tags]
