sculpin:
    ignore:
        - 'assets/images/*/originals/*'
sculpin_content_types:
    posts:
        permalink: blog/:slug_title/
        taxonomies:
            - tags
    projects:
        permalink: portfolio/:slug_title/
        taxonomies:
            - skills
            - tags
    talks:
        permalink: talks/:filename/
        taxonomies:
            - tags
