title: 'Oliver Davies'
subtitle: 'Web Developer, System Administrator - PHP, Drupal, Symfony, Linux'
description: 'Oliver Davies, Drupal Developer'
default_date_format: 'jS F, Y'
fuzzy_date_format: F Y
apple_touch_icon_sizes: [ 57, 114, 72, 144, 60, 120, 76, 152 ]
favicon_sizes: [ 160, 96, 32, 16 ]

ansible_galaxy:
    url: https://galaxy.ansible.com/opdavies

author:
    name: Oliver Davies
    bio: 'Oliver Davies is a Drupal Developer and System Administrator based in the UK. He is a Senior Developer at <a href="https://www.appnovation.com">Appnovation</a> and also provides freelance consultancy services for Drupal websites, PHP applications and Linux servers.'
    company:
        logo: appnovation.png
        name: Appnovation
        name_short: Appnovation
        role: Senior Drupal Developer
        website: https://www.appnovation.com

availability:
    part: limited
    full: no

companies:
    appnovation:
        name: Appnovation Technologies
        website: https://www.appnovation.com
        logo: appnovation.png
    cti:
        name: CTI Digital
        website: https://www.ctidigital.com
        logo: cti-digital.png
    drupal_association:
        name: Drupal Association
        website: https://assoc.drupal.org
        logo: drupal-association.png
    freelance:
        name: Freelance
    horse_country:
        name: 'Horse & Country TV'
        logo: horse-and-country.jpg
        website: http://www.horseandcountry.tv
    lab_class:
        name: Lab Class
        website: http://labclass.co.uk
        logo: lab-class.png
    microserve:
        name: Microserve
        website: https://microserve.io
        logo: microserve.png
    nomensa:
        name: Nomensa
        website: http://www.nomensa.com
        logo: nomensa.png
    precedent:
        name: Precedent
        website: http://precedent.com
        logo: precedent.jpg
    proctors:
        name: 'Proctor & Stevenson'
        website: http://www.proctors.co.uk
        logo: proctors.jpg
    trent:
        name: Trent Design
        website: http://www.trentdesign.net
    zooba:
        name: Zooba Ltd

drupalorg:
    name: opdavies
    uid: 381388
    url: https://www.drupal.org/user/381388
    url_nice: https://www.drupal.org/u/opdavies

email: oliver+website@oliverdavies.uk

github:
    name: opdavies
    url: http://github.com/opdavies

gravatar:
    url: //www.gravatar.com/avatar/e0f6adcd63d8393e689b327e978d0887.png

irc:
    name: opdavies

joindin:
    url: https://joind.in/user/opdavies

lanyrd:
    url: http://lanyrd.com/profile/opdavies

latest_posts: 3

linkedin:
    url: http://uk.linkedin.com/in/opdavies

meetups:
    drupalbristol:
        name: Drupal Bristol
        logo: drupal-bristol.jpeg
        website: http://www.drupalbristol.org.uk
    drupalcampbristol:
        name: DrupalCamp Bristol
        website: http://www.drupalcampbristol.co.uk
        logo: drupalcamp-bristol.png
    swdug:
        name: SWDUG
        logo: swdug.png
        website: http://swdug.org.uk
    phpsw:
        name: PHPSW
        logo: phpsw.jpeg
        website: http://phpsw.uk

packagist:
    name: opdavies
    url: https://packagist.org/users/opdavies

skills:
    compass: { title: Compass, image: compass.png }
    drupal: { title: Drupal, image: drupal.png }
    drupal-commerce: { title: Drupal Commerce, image: drupal-commerce.png }
    git: { title: Git, image: git.png }
    jenkins: { title: Jenkins, image: jenkins.png }
    less: { title: Less, image: less.png }
    php: { title: PHP, image: php.png }
    sass: { title: Sass, image: sass.png }
    svn: { title: Subversion, image: svn.jpg }

speakerdeck:
    url: https://speakerdeck.com/opdavies

twitter:
    name: opdavies
    url: https://twitter.com/opdavies

wordpress:
    name: opdavies
    url: https://profiles.wordpress.org/opdavies

youtube:
    channel_url: https://www.youtube.com/channel/UCkeK0qF9HHUPQH_fvn4ghqQ

talks_events:
    drupal-bristol: { title: Drupal Bristol, website: https://www.drupalbristol.org.uk }
    drupalcamp-brighton-2015: { title: DrupalCamp Brighton 2015, website: http://2015.drupalcampbrighton.co.uk }
    drupalcamp-bristol-2016: { title: DrupalCamp Bristol 2016, website: https://www.drupalcampbristol.org.uk }
    drupalcamp-london-2014: { title: DrupalCamp London 2014, website: https://drupalcamp.london }
    drupalcamp-london-2015: { title: DrupalCamp London 2015, website: https://drupalcamp.london }
    drupalcamp-london-2016: { title: DrupalCamp London 2016, website: https://drupalcamp.london }
    drupalcamp-london-2017: { title: DrupalCamp London 2017 }
    drupalcamp-north-2015: { title: DrupalCamp North 2015 }
    nwdug: { title: NWDUG }
    phpsc-16: { title: PHP South Coast 2016, website: http://2016.phpsouthcoast.co.uk }
    phpsw: { title: PHPSW, website: https://phpsw.uk }
    swdug: { title: 'SWDUG (South Wales Drupal user group)' }
    umbristol: { title: 'umBristol (Bristol Umbraco user group)' }
    udiff: { title: Unified Diff }
