sculpin:
    ignore: ['**/.DS*', '**/*.swp']

sculpin_content_types:
    posts:
        permalink: articles/:basename/
        taxonomies: [tags]
    talks:
        permalink: talks/:basename/
        taxonomies: [tags]

services:
    App\TwigExtension\Talk\TalksExtension:
        tags:
            - { name: twig.extension }
