sculpin:
    permalink: pretty

sculpin_content_types:
    posts:
        permalink: blog/:slug_title/
        taxonomies:
            - tags
    talks:
        permalink: talks/:slug_title/
        taxonomies:
            - tags
