title: 'Oliver Davies'
subtitle: 'Web Developer, System Administrator - PHP, Drupal, Symfony, Linux'
description: 'Oliver Davies, Drupal Developer'
default_date_format: 'jS F, Y'
fuzzy_date_format: F Y
apple_touch_icon_sizes: [ 57, 114, 72, 144, 60, 120, 76, 152 ]
favicon_sizes: [ 160, 96, 32, 16 ]

nav_links:
    - { title: About, href: '/', pattern: '/\.' }
    - { title: Experience, href: '/experience' }
    - { title: Testimonials, href: '/testimonials' }
    - { title: Talks, href: '/talks' }
    - { title: Blog, href: '/blog' }
    - { title: Contact, href: '/contact' }

ansible_galaxy:
    url: https://galaxy.ansible.com/opdavies

availability:
    part: no
    full: no

avatar:
    url: /assets/images/me-precedent.jpg

drupalorg:
    name: opdavies
    uid: 381388
    url: https://www.drupal.org/user/381388
    url_new: https://www.drupal.org/u/opdavies

email: oliver+website@oliverdavies.uk

github:
    name: opdavies
    url: http://github.com/opdavies

gravatar:
    url: //www.gravatar.com/avatar/e0f6adcd63d8393e689b327e978d0887.png

irc:
    name: opdavies

joindin:
    url: https://joind.in/user/opdavies

lanyrd:
    url: http://lanyrd.com/profile/opdavies

latest_posts: 3

linkedin:
    url: http://uk.linkedin.com/in/opdavies

packagist:
    name: opdavies
    url: https://packagist.org/users/opdavies

speakerdeck:
    url: https://speakerdeck.com/opdavies

twitter:
    name: opdavies
    url: https://twitter.com/opdavies

wordpress:
    name: opdavies
    url: https://profiles.wordpress.org/opdavies

youtube:
    channel_url: https://www.youtube.com/channel/UCkeK0qF9HHUPQH_fvn4ghqQ

work:
    role: Senior Developer
    company: microserve

companies:
    appnovation:
        name: Appnovation
        logo: appnovation.png
        url: https://www.appnovation.com

    cti:
        name: CTI Digital
        logo: cti-digital.png
        url: https://www.ctidigital.com

    drupal_association:
        name: Drupal Association
        logo: drupal-association.png
        url: https://assoc.drupal.org

    freelance:
        name: Freelance

    horse_country:
        name: 'Horse & Country TV'
        logo: horse-and-country.jpg
        url: http://www.horseandcountry.tv

    lab_class:
        name: Lab Class
        logo: lab-class.png
        url: http://labclass.co.uk

    microserve:
        name: Microserve
        logo: microserve.png
        url: https://microserve.io

    nomensa:
        name: Nomensa
        logo: nomensa.png
        url: http://www.nomensa.com

    precedent:
        name: Precedent
        logo: precedent.jpg
        url: http://precedent.com

    proctors:
        name: 'Proctor & Stevenson'
        logo: proctors.jpg
        url: http://www.proctors.co.uk

    trent:
        name: Trent Design
        url: http://www.trentdesign.net

    zooba:
        name: Zooba Ltd

meetups:
    - name: Drupal Bristol
      logo: drupal-bristol.jpeg
      url: 'http://www.drupalbristol.org.uk'

    - name: DrupalCamp Bristol
      logo: drupalcamp-bristol.png
      url: 'http://www.drupalcampbristol.co.uk'

    - name: PHPSW
      logo: phpsw.jpeg
      url: 'http://phpsw.uk'

events:
    drupal-bristol:
        name: Drupal Bristol
        location: Bristol, UK
        website: https://www.drupalbristol.org.uk

    drupal-somerset:
        name: Drupal Somerset
        location: Glastonbury, UK

    drupalcamp-brighton-15:
        name: DrupalCamp Brighton 2015
        location: Brighton, UK

    drupalcamp-bristol-16:
        name: DrupalCamp Bristol 2016
        location: Bristol, UK
        website: https://2016.drupalcampbristol.org.uk

    drupalcamp-dublin-17:
        name: DrupalCamp Dublin 2017
        location: Dublin, Ireland
        website: http://2017.drupal.ie

    drupalcamp-london-14:
        name: DrupalCamp London 2014
        location: London, UK

    drupalcamp-london-15:
        name: DrupalCamp London 2015
        location: London, UK

    drupalcamp-london-16:
        name: DrupalCamp London 2016
        location: London, UK

    drupalcamp-london-17:
        name: DrupalCamp London 2017
        location: London, UK
        website: http://drupalcamp.london

    drupalcamp-north-15:
        name: DrupalCamp North 2015
        location: Sunderland, UK
        website: http://drupalcampnorth.org

    nomad-php:
        name: Nomad PHP
        location: Online
        website: https://nomadphp.com

    nwdug:
        name: NWDUG
        location: Manchester, UK
        website: http://nwdrupal.org.uk

    phpnw17:
        name: PHP North West 2017
        location: Manchester, UK
        website: http://conference.phpnw.org.uk/phpnw17

    phpsc16:
        name: PHP South Coast 2016
        location: Portsmouth, UK
        website: http://2016.phpsouthcoast.co.uk

    phpsw:
        name: PHPSW
        location: Bristol, UK
        website: https://phpsw.uk

    swdug:
        name: SWDUG
        location: Cardiff, UK

    umbristol:
        name: umBristol
        location: Bristol, UK
        website: http://umbristol.co.uk

    unifieddiff:
        name: 'unified.diff'
        location: Cardiff, UK
        website: http://unifieddiff.co.uk
