sculpin:
    ignore: ['**/.DS*', '**/*.swp']

sculpin_content_types:
    pages:
        permalink: /:basename/
    posts:
        permalink: articles/:basename/
        taxonomies: [tags]
    talks:
        permalink: talks/:basename/
        taxonomies: [tags]

services:
    App\Talk\TwigExtension\TalksExtension:
        tags:
            - { name: twig.extension }
