title: Oliver Davies
subtitle: Drupal Developer & System Administrator
description: Oliver Davies, Drupal Developer

author: Oliver Davies
email: oliver+website@oliverdavies.uk

twitter:
    url: http://twitter.com/opdavies
    name: opdavies
linkedin:
    url: http://uk.linkedin.com/in/opdavies
drupalorg:
    url: https://www.drupal.org/user/381388
    url_nice: https://www.drupal.org/u/opdavies
    name: opdavies
github:
    url: http://github.com/opdavies
    name: opdavies
irc:
    name: opdavies
lanyrd:
    url: http://lanyrd.com/profile/opdavies
joindin:
    url: https://joind.in/user/view/27119
ansible_galaxy:
    url: https://galaxy.ansible.com/list#/users/14560
gravatar:
    url: http://www.gravatar.com/avatar/e0f6adcd63d8393e689b327e978d0887.png
flickr:
    url: https://www.flickr.com/photos/133286555@N04
speakerdeck:
    url: https://speakerdeck.com/opdavies

apple_touch_icon_sizes: [ 57, 114, 72, 144, 60, 120, 76, 152 ]
favicon_sizes: [ 160, 96, 32, 16 ]

main_menu:
    - { title: Services, href: /services/ }
    - { title: Testimonials, href: /testimonials/ }
    - { title: Talks, href: /talks/ }
    - { title: Blog, href: /blog/ }
    - { title: Contact, href: /contact/ }

meetups:
    swdug: { name: SWDUG, logo: swdug.png, url: http://swdug.org.uk }
    drupalbristol: { name: Drupal Bristol, logo: drupal-bristol.jpeg, url: https://groups.drupal.org/bristol-west-uk }
    phpsw: { name: PHPSW, logo: phpsw.jpeg, url: http://phpsw.uk }
    swlug: { name: SWLUG, logo: swlug.png, url: http://swlug.org.uk }
    accbristol: { name: Accessible Bristol, logo: accessible-bristol.png, url: http://www.accessiblebristol.org.uk }
    udiff: { name: Unified Diff, logo: unified-diff.png, url: http://unifieddiff.co.uk }

hightlightjs_style: default
digitalocean_referral: a913b4b00d4a
default_date_format: jS F, Y
title_separator: "|"

availability:
    status:
        day:
            available: no
            start: ~
            end: ~
        evenings:
            available: limited
            start: 2015-08-10
            end: ~
    text:
        day:
            yes: Available for day contract work
            no: Not available for day contract work
        evenings:
            yes: Available for weekend/evening freelance work
            no: Not availabile for weekend/evening freelance work
            limited: Limited availability for weekend/evening freelance work
