title: 'Oliver Davies'
subtitle: 'Web Developer, System Administrator - PHP, Drupal, Symfony, Linux'
description: 'Oliver Davies, Drupal Developer'
default_date_format: 'jS F, Y'
fuzzy_date_format: F Y
apple_touch_icon_sizes: [ 57, 114, 72, 144, 60, 120, 76, 152 ]
favicon_sizes: [ 160, 96, 32, 16 ]

ansible_galaxy:
    url: https://galaxy.ansible.com/opdavies

availability:
    part: limited
    full: no

companies:
    appnovation:        { name: Appnovation,           logo: appnovation.png,        website: https://www.appnovation.com }
    cti:                { name: CTI Digital,           logo: cti-digital.png,        website: https://www.ctidigital.com }
    drupal_association: { name: Drupal Association,    logo: drupal-association.png, website: https://assoc.drupal.org }
    freelance:          { name: Freelance,             logo: ~,                      website: ~ }
    horse_country:      { name: 'Horse & Country TV',  logo: horse-and-country.jpg,  website: http://www.horseandcountry.tv }
    lab_class:          { name: Lab Class,             logo: lab-class.png,          website: http://labclass.co.uk }
    microserve:         { name: Microserve,            logo: microserve.png,         website: https://microserve.io }
    nomensa:            { name: Nomensa,               logo: nomensa.png,            website: http://www.nomensa.com }
    precedent:          { name: Precedent,             logo: precedent.jpg,          website: http://precedent.com }
    proctors:           { name: 'Proctor & Stevenson', logo: proctors.jpg,           website: http://www.proctors.co.uk }
    trent:              { name: Trent Design,          logo: ~,                      website: http://www.trentdesign.net }
    zooba:              { name: Zooba Ltd,             logo: ~,                      website: ~ }

drupalorg:
    name: opdavies
    uid: 381388
    url: https://www.drupal.org/user/381388
    url_nice: https://www.drupal.org/u/opdavies

email: oliver+website@oliverdavies.uk

events:
    drupal-bristol:           { title: Drupal Bristol,           location: 'Bristol, UK',    website: https://www.drupalbristol.org.uk }
    drupalcamp-brighton-2015: { title: DrupalCamp Brighton 2015, location: 'Brighton, UK',   website: ~ }
    drupalcamp-bristol-2016:  { title: DrupalCamp Bristol 2016,  location: 'Bristol, UK',    website: https://www.drupalcampbristol.org.uk }
    drupalcamp-london-2014:   { title: DrupalCamp London 2014,   location: 'London, UK',     website: ~ }
    drupalcamp-london-2015:   { title: DrupalCamp London 2015,   location: 'London, UK',     website: ~ }
    drupalcamp-london-2016:   { title: DrupalCamp London 2016,   location: 'London, UK',     website: ~ }
    drupalcamp-london-2017:   { title: DrupalCamp London 2017,   location: 'London, UK',     website: https://drupalcamp.london }
    drupalcamp-north-2015:    { title: DrupalCamp North 2015,    location: 'Sunderland, UK', website: http://drupalcampnorth.org }
    nwdug:                    { title: NWDUG,                    location: 'Manchester, UK', website: http://nwdrupal.org.uk }
    phpsc-16:                 { title: PHP South Coast 2016,     location: 'Portsmouth, UK', website: http://2016.phpsouthcoast.co.uk }
    phpsw:                    { title: PHPSW,                    location: 'Bristol, UK',    website: https://phpsw.uk }
    swdug:                    { title: 'SWDUG',                  location: 'Cardiff, UK',    website: ~ }
    udiff:                    { title: Unified Diff,             location: 'Cardiff, UK',    website: http://unifieddiff.co.uk }
    umbristol:                { title: 'umBristol',              location: 'Bristol, UK',    website: http://umbristol.co.uk }

github:
    name: opdavies
    url: http://github.com/opdavies

gravatar:
    url: //www.gravatar.com/avatar/e0f6adcd63d8393e689b327e978d0887.png

irc:
    name: opdavies

joindin:
    url: https://joind.in/user/opdavies

lanyrd:
    url: http://lanyrd.com/profile/opdavies

latest_posts: 3

linkedin:
    url: http://uk.linkedin.com/in/opdavies

meetups:
    drupalbristol:     { name: Drupal Bristol,     logo: drupal-bristol.jpeg,    website: http://www.drupalbristol.org.uk }
    drupalcampbristol: { name: DrupalCamp Bristol, logo: drupalcamp-bristol.png, website: http://www.drupalcampbristol.co.uk }
    phpsw:             { name: PHPSW,              logo: phpsw.jpeg,             website: http://phpsw.uk }
    swdug:             { name: SWDUG,              logo: swdug.png,              website: http://swdug.org.uk }

packagist:
    name: opdavies
    url: https://packagist.org/users/opdavies

skills:
    compass:         { title: Compass,         image: compass.png }
    drupal:          { title: Drupal,          image: drupal.png }
    drupal-commerce: { title: Drupal Commerce, image: drupal-commerce.png }
    git:             { title: Git,             image: git.png }
    jenkins:         { title: Jenkins,         image: jenkins.png }
    less:            { title: Less,            image: less.png }
    php:             { title: PHP,             image: php.png }
    sass:            { title: Sass,            image: sass.png }
    svn:             { title: Subversion,      image: svn.jpg }

speakerdeck:
    url: https://speakerdeck.com/opdavies

twitter:
    name: opdavies
    url: https://twitter.com/opdavies

wordpress:
    name: opdavies
    url: https://profiles.wordpress.org/opdavies

youtube:
    channel_url: https://www.youtube.com/channel/UCkeK0qF9HHUPQH_fvn4ghqQ

work:
    role: Senior Drupal Developer
    company: microserve
