version: 2

jobs:
    build_and_test:
        docker:
            - image: php:7.1
        steps:
            - checkout
            - run: composer install
            - run: ./vendor/bin/phpunit

workflows:
    version: 2
    build_test_and_deploy:
        jobs:
            - build_and_test
