---
- name: Install Composer dependencies
  composer:
   command: install
   working_dir: "{{ ansistrano_release_path.stdout }}"

- name: Generate the site once without assets
  command: composer run prod chdir={{ ansistrano_release_path.stdout }}

- name: Install Node dependencies
  command: yarn install chdir={{ ansistrano_release_path.stdout }}

- name: Generate assets
  command: yarn run encore production chdir={{ ansistrano_release_path.stdout }}

- name: Generate the site, including assets
  command: composer run prod chdir={{ ansistrano_release_path.stdout }}
