services:
    app.twig.speakerdeck:
        class: AppBundle\Twig\SpeakerDeckExtension
        tags:
            - { name: twig.extension }
    app.twig.tweet:
        class: AppBundle\Twig\TweetExtension
        tags:
            - { name: twig.extension }
    app.twig.vimeo:
        class: AppBundle\Twig\VimeoExtension
        tags:
            - { name: twig.extension }
    app.twig.youtube:
        class: AppBundle\Twig\YouTubeExtension
        tags:
            - { name: twig.extension }
