---
- hosts: all
  become: true

  vars_files:
    - ./vars/main.yml

  tasks:
    - synchronize:
        src: ../output_prod/
        dest: '/srv/{{ server_name }}'
        delete: yes
        recursive: yes
