---
- hosts: web

  vars_prompt:
    - name: git_branch
      prompt: 'Enter a branch to deploy'
      default: master
      private: false

  vars:
    ansistrano_deploy_to: /var/www/oliverdavies.uk
    ansistrano_deploy_via: git
    ansistrano_git_repo: https://github.com/opdavies/oliverdavies.uk.git
    ansistrano_shared_paths:
      - node_modules
    ansistrano_keep_releases: 3
    ansistrano_allow_anonymous_stats: false
    ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/deploy/after-symlink-shared.yml"
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/deploy/after-symlink.yml"

  roles:
    - carlosbuenosvinos.ansistrano-deploy
